// <auto-generated />
namespace RoofTop.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Update3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update3));
        
        string IMigrationMetadata.Id
        {
            get { return "201504302229082_Update3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
